// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pokemon.sql

package database

import (
	"context"
)

const addOwnedPokemon = `-- name: AddOwnedPokemon :one
INSERT INTO ownpoke (
    trainer_id,
    name,
    height,
    weight,
    base_experience,
    stats,
    types
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, trainer_id, name, height, weight, base_experience, stats, types, caught_at
`

type AddOwnedPokemonParams struct {
	TrainerID      int32  `json:"trainer_id"`
	Name           string `json:"name"`
	Height         int32  `json:"height"`
	Weight         int32  `json:"weight"`
	BaseExperience int32  `json:"base_experience"`
	Stats          []byte `json:"stats"`
	Types          []byte `json:"types"`
}

func (q *Queries) AddOwnedPokemon(ctx context.Context, arg AddOwnedPokemonParams) (Ownpoke, error) {
	row := q.db.QueryRow(ctx, addOwnedPokemon,
		arg.TrainerID,
		arg.Name,
		arg.Height,
		arg.Weight,
		arg.BaseExperience,
		arg.Stats,
		arg.Types,
	)
	var i Ownpoke
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.Name,
		&i.Height,
		&i.Weight,
		&i.BaseExperience,
		&i.Stats,
		&i.Types,
		&i.CaughtAt,
	)
	return i, err
}

const createPokedexEntry = `-- name: CreatePokedexEntry :exec
INSERT INTO pokedex (
    trainer_id,
    name,
    height,
    weight,
    base_experience,
    stats,
    types
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) 
ON CONFLICT (trainer_id, name) DO NOTHING
`

type CreatePokedexEntryParams struct {
	TrainerID      int32  `json:"trainer_id"`
	Name           string `json:"name"`
	Height         int32  `json:"height"`
	Weight         int32  `json:"weight"`
	BaseExperience int32  `json:"base_experience"`
	Stats          []byte `json:"stats"`
	Types          []byte `json:"types"`
}

func (q *Queries) CreatePokedexEntry(ctx context.Context, arg CreatePokedexEntryParams) error {
	_, err := q.db.Exec(ctx, createPokedexEntry,
		arg.TrainerID,
		arg.Name,
		arg.Height,
		arg.Weight,
		arg.BaseExperience,
		arg.Stats,
		arg.Types,
	)
	return err
}

const deletePokedexEntry = `-- name: DeletePokedexEntry :exec
DELETE FROM pokedex
WHERE id = $1
`

func (q *Queries) DeletePokedexEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePokedexEntry, id)
	return err
}

const getPokedexEntry = `-- name: GetPokedexEntry :one
SELECT id, trainer_id, name, height, weight, base_experience, stats, types, created_at, updated_at FROM pokedex
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPokedexEntry(ctx context.Context, id int32) (Pokedex, error) {
	row := q.db.QueryRow(ctx, getPokedexEntry, id)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.Name,
		&i.Height,
		&i.Weight,
		&i.BaseExperience,
		&i.Stats,
		&i.Types,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPokedexEntryByNameAndTrainer = `-- name: GetPokedexEntryByNameAndTrainer :one
SELECT id, trainer_id, name, height, weight, base_experience, stats, types, created_at, updated_at FROM pokedex
WHERE name = $1 AND trainer_id = $2 LIMIT 1
`

type GetPokedexEntryByNameAndTrainerParams struct {
	Name      string `json:"name"`
	TrainerID int32  `json:"trainer_id"`
}

func (q *Queries) GetPokedexEntryByNameAndTrainer(ctx context.Context, arg GetPokedexEntryByNameAndTrainerParams) (Pokedex, error) {
	row := q.db.QueryRow(ctx, getPokedexEntryByNameAndTrainer, arg.Name, arg.TrainerID)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.Name,
		&i.Height,
		&i.Weight,
		&i.BaseExperience,
		&i.Stats,
		&i.Types,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnedPokemonByTrainer = `-- name: ListOwnedPokemonByTrainer :many
SELECT id, trainer_id, name, height, weight, base_experience, stats, types, caught_at FROM ownpoke
WHERE trainer_id = $1
ORDER BY caught_at DESC
`

func (q *Queries) ListOwnedPokemonByTrainer(ctx context.Context, trainerID int32) ([]Ownpoke, error) {
	rows, err := q.db.Query(ctx, listOwnedPokemonByTrainer, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ownpoke{}
	for rows.Next() {
		var i Ownpoke
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Name,
			&i.Height,
			&i.Weight,
			&i.BaseExperience,
			&i.Stats,
			&i.Types,
			&i.CaughtAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPokedexByTrainer = `-- name: ListPokedexByTrainer :many
SELECT id, trainer_id, name, height, weight, base_experience, stats, types, created_at, updated_at FROM pokedex
WHERE trainer_id = $1
ORDER BY id
`

func (q *Queries) ListPokedexByTrainer(ctx context.Context, trainerID int32) ([]Pokedex, error) {
	rows, err := q.db.Query(ctx, listPokedexByTrainer, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pokedex{}
	for rows.Next() {
		var i Pokedex
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Name,
			&i.Height,
			&i.Weight,
			&i.BaseExperience,
			&i.Stats,
			&i.Types,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
