// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePokemon(ctx context.Context, arg CreatePokemonParams) (Pokemon, error)
	CreateTrainer(ctx context.Context, name pgtype.Text) (Trainer, error)
	DeletePokemon(ctx context.Context, id int32) error
	GetPokemon(ctx context.Context, id int32) (Pokemon, error)
	GetPokemonByNameAndTrainer(ctx context.Context, arg GetPokemonByNameAndTrainerParams) (Pokemon, error)
	GetTrainer(ctx context.Context, id int32) (Trainer, error)
	GetTrainerByName(ctx context.Context, name pgtype.Text) (Trainer, error)
	ListPokemonByTrainer(ctx context.Context, trainerID int32) ([]Pokemon, error)
	ListTrainers(ctx context.Context, arg ListTrainersParams) ([]Trainer, error)
	UpdateTrainer(ctx context.Context, arg UpdateTrainerParams) (Trainer, error)
}

var _ Querier = (*Queries)(nil)
